"""Local-Ollama-driven conversation summary for long MACS chats.

Why: Claude Code stores the full transcript in JSONL. When a chat grows past
~50KB, the spawned `claude -p --resume <sid>` model has to skim through tons
of tool output + safety wrappers to find the actual user intent. This module
distills the chat into a 1-page brief that MACS injects at the top of every
new turn, alongside the per-chat handover note (Phase 1).

Tradeoff: the summary is generated by gemma3:4b (small + fast + local). It
WILL miss nuance — but it gives the next Claude spawn a clear "what's the
shape of this conversation" anchor that the literal transcript doesn't.

Run model: gemma3:4b (~5s/generate). Triggered in a background thread so
stream completion isn't delayed.
"""
import json
import re
import time
import urllib.request
from pathlib import Path
from typing import Optional, Tuple

from sessions import session_dir, strip_injected_preamble

OLLAMA_URL = "http://localhost:11434/api/generate"
# qwen3:8b has more context room than gemma3:4b (which 8k-truncates and
# returns "Okay" on long inputs). Slower (~12s vs 5s) but reliable on
# real chats.
SUMMARY_MODEL = "qwen3:8b"
SUMMARY_TIMEOUT_S = 90

# How big the conversation must be before we run a summary at all
MIN_TRANSCRIPT_BYTES = 50_000
# Don't re-summarize unless transcript grew by at least this much OR
# enough time has passed since last summary (cheaper than re-running every turn).
REGEN_GROW_BYTES = 30_000
REGEN_MAX_AGE_S = 60 * 60 * 4  # 4h

# Keep input well under context. Conservative: ~6000 tokens ≈ 18000 chars.
# Anything larger gets head-trimmed (we keep the recent tail).
MAX_INPUT_CHARS = 18_000
MAX_SUMMARY_CHARS = 3_500       # cap summary file size on disk
INJECT_TAIL_CHARS = 2_500       # injected portion (full file is usually within)


def _summary_path(project_path: str, session_id: str) -> Path:
    return Path(project_path) / ".macs" / "chats" / f"{session_id}.summary.md"


def read_summary_tail(project_path: str, session_id: Optional[str]) -> Optional[str]:
    """Return the most recent summary text for injection. None if missing."""
    if not session_id:
        return None
    sp = _summary_path(project_path, session_id)
    if not sp.is_file():
        return None
    try:
        data = sp.read_text(encoding="utf-8", errors="replace")
        return data[-INJECT_TAIL_CHARS:]
    except OSError:
        return None


def _condense_transcript(project_path: str, session_id: str) -> Tuple[str, int]:
    """Read JSONL, extract human-readable turn-by-turn text (no tool JSON, no
    safety wrappers). Returns (text, message_count)."""
    sdir = session_dir(project_path)
    f = sdir / f"{session_id}.jsonl"
    if not f.is_file():
        return "", 0

    lines: list[str] = []
    msg_count = 0
    with f.open("r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            try:
                evt = json.loads(raw)
            except json.JSONDecodeError:
                continue
            t = evt.get("type")
            msg = evt.get("message") or {}
            content = msg.get("content")
            if t == "user":
                txt = ""
                if isinstance(content, str):
                    txt = content
                elif isinstance(content, list):
                    parts = [b.get("text", "") for b in content if b.get("type") == "text"]
                    txt = "\n".join(parts)
                txt = strip_injected_preamble(txt).strip()
                if txt:
                    lines.append(f"USER: {txt[:1200]}")
                    msg_count += 1
            elif t == "assistant" and isinstance(content, list):
                parts = []
                for b in content:
                    if b.get("type") == "text":
                        parts.append(b.get("text", ""))
                    elif b.get("type") == "tool_use":
                        nm = b.get("name", "?")
                        inp = b.get("input") or {}
                        # one-line tool use summary
                        if nm in ("Bash",):
                            cmd = (inp.get("command") or "")[:120]
                            parts.append(f"[tool:Bash] {cmd}")
                        elif nm in ("Edit", "Write"):
                            fp = inp.get("file_path") or inp.get("path") or "?"
                            parts.append(f"[tool:{nm}] {fp}")
                        elif nm in ("Read",):
                            fp = inp.get("file_path") or inp.get("path") or "?"
                            parts.append(f"[tool:Read] {fp}")
                        elif nm in ("TaskCreate",):
                            subj = (inp.get("subject") or "")[:100]
                            parts.append(f"[tool:TaskCreate] {subj}")
                        elif nm in ("TaskUpdate",):
                            tid = inp.get("taskId")
                            st = inp.get("status")
                            parts.append(f"[tool:TaskUpdate] #{tid} → {st}")
                        else:
                            parts.append(f"[tool:{nm}]")
                txt = "\n".join(p for p in parts if p.strip()).strip()
                if txt:
                    lines.append(f"ASSISTANT: {txt[:1500]}")
                    msg_count += 1

    out = "\n\n".join(lines)
    # Keep the most recent end of the conversation under the budget
    if len(out) > MAX_INPUT_CHARS:
        out = "[...earlier conversation trimmed...]\n\n" + out[-MAX_INPUT_CHARS:]
    return out, msg_count


_SUMMARY_PROMPT = """Below is a chat transcript between a user (Indonesian/English mixed) and an AI coding assistant. Produce a focused brief that helps a NEW assistant pick up the conversation cold without re-reading the full transcript.

Output format (markdown, ~400 words max):

## Original ask
One paragraph: what the user wanted at the start of this chat.

## What's been done
3-6 bullets: concrete deliverables already shipped (files written, endpoints added, fixes landed). Skip exploratory dead ends.

## Current focus
1-2 bullets: what's actively being worked on right now (or last worked on before the conversation went idle).

## Decisions made
Bullets: design choices, trade-offs, constraints the user agreed to. Skip if none.

## Open threads
Bullets: things still pending, blockers, or things the user mentioned wanting later.

## How to address the user
1 line: tone, language preference, special rules they enforced (e.g., "user speaks casual Indonesian; closes turns with STATUS block").

Be terse. Skip section if nothing meaningful to say.

Transcript:
---
"""


_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)


def _call_ollama(transcript: str) -> Optional[str]:
    """Single-shot summarize call to local Ollama. Returns None on any failure."""
    # qwen3:8b is a "thinking" model — disable internal reasoning via /no_think
    # so the response is just the brief, not chain-of-thought.
    prompt = _SUMMARY_PROMPT + transcript + "\n---\n/no_think\n"
    try:
        payload = json.dumps({
            "model": SUMMARY_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.2,
                "num_predict": 800,
            },
        }).encode("utf-8")
        req = urllib.request.Request(
            OLLAMA_URL,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=SUMMARY_TIMEOUT_S) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
        data = json.loads(raw)
        out = (data.get("response") or "").strip()
        # Defensive: strip <think>...</think> blocks if model emitted them despite /no_think
        out = _THINK_RE.sub("", out).strip()
        return out or None
    except Exception as e:
        print(f"[summarizer] ollama call failed: {e}")
        return None


def should_summarize(project_path: str, session_id: str) -> Tuple[bool, str]:
    """Decide if we should (re)generate the summary for this chat.

    Returns (should, reason)."""
    sdir = session_dir(project_path)
    jsonl = sdir / f"{session_id}.jsonl"
    if not jsonl.is_file():
        return False, "no jsonl"
    try:
        jsize = jsonl.stat().st_size
    except OSError:
        return False, "stat failed"
    if jsize < MIN_TRANSCRIPT_BYTES:
        return False, f"transcript too small ({jsize}B < {MIN_TRANSCRIPT_BYTES}B)"

    sf = _summary_path(project_path, session_id)
    if not sf.is_file():
        return True, "no summary yet"
    try:
        smt = sf.stat().st_mtime
        smsize = sf.stat().st_size
    except OSError:
        return True, "summary stat failed"
    age = time.time() - smt
    # Grow heuristic: approximate by transcript size, since summary file is
    # capped — what we care about is "did the chat grow a lot since last build".
    jmt = jsonl.stat().st_mtime
    if jmt <= smt:
        return False, "transcript not changed since last summary"
    # Look at how many bytes were appended (approx via mtime gap and current size).
    # Conservative: require either >REGEN_GROW_BYTES growth OR REGEN_MAX_AGE_S elapsed.
    grew = max(0, jsize - smsize * 18)  # rough "transcript should be ~18× summary"
    if grew >= REGEN_GROW_BYTES:
        return True, f"grew ~{grew}B"
    if age >= REGEN_MAX_AGE_S:
        return True, f"summary age {int(age)}s > {REGEN_MAX_AGE_S}s"
    return False, f"recent summary ({int(age)}s old, size diff {grew}B)"


def build_and_write_summary(project_path: str, session_id: str) -> Optional[str]:
    """Synchronous: condense → ollama → write file. Returns the summary text
    on success (None on failure). Safe to call in a background thread."""
    text, msg_count = _condense_transcript(project_path, session_id)
    if not text or msg_count < 4:
        return None
    summary = _call_ollama(text)
    if not summary:
        return None
    header = (
        f"# Conversation summary · {session_id[:8]}\n"
        f"_Built: {time.strftime('%Y-%m-%d %H:%M:%S %Z')} · {msg_count} messages distilled by {SUMMARY_MODEL}_\n\n"
    )
    body = header + summary
    if len(body) > MAX_SUMMARY_CHARS:
        body = body[:MAX_SUMMARY_CHARS] + "\n[...truncated]\n"
    sf = _summary_path(project_path, session_id)
    try:
        sf.parent.mkdir(parents=True, exist_ok=True)
        sf.write_text(body, encoding="utf-8")
        return body
    except OSError as e:
        print(f"[summarizer] write failed: {e}")
        return None


def maybe_summarize_async(project_path: str, session_id: Optional[str]) -> None:
    """Fire-and-forget: check if summary is due; if so, build it in a
    background thread so we don't block the streaming pipeline."""
    if not session_id:
        return
    ok, reason = should_summarize(project_path, session_id)
    if not ok:
        return

    import threading

    def _runner():
        try:
            t0 = time.time()
            res = build_and_write_summary(project_path, session_id)
            if res:
                print(f"[summarizer] wrote summary for {session_id[:8]} in {time.time()-t0:.1f}s ({reason})")
        except Exception as e:
            print(f"[summarizer] background runner failed: {e}")

    th = threading.Thread(target=_runner, daemon=True, name=f"summarize-{session_id[:8]}")
    th.start()
